# Feel free to translate this to your native language
[flux]
 energystat = "Energy: %s / %s F"
 gen = "Generating %s F/t"
 usage = "Using %s F/t"
 update = "Flux has a newer version: %s"
 works_underwater = "It even works underwater!"
 recipe_compat = "Using compatible recipe! It may be unstable!"

[flux.book]
 name = "Flux Book"
 landing_text = "A manual for Flux."

[flux.gift]
 invalid = "Invalid Gift!"
 received = "You just received a Flux Gift!"

[flux.chip]
 speed = "Speed"
 energy = "Energy"

[flux.configgui]
 fluxGenBaseEnergyValue = "Base energy generation for Flux Generator"
 basicMachineEU = "Energy usage for basic machines (Grinding Mill, Washer, etc.)"

[item.flux]
 mftool = "Flux Tool"
 gift = "Flux Gift"
 machine_base = "Machine Base"
 chip = "Flux Chip"
 seal = "Flux Seal"
 glue = "Flux Glue"
 paste = "Flux Paste"
 iron_grit = "Iron Grit"
 gold_grit = "Gold Grit"
 copper_grit = "Copper Grit"
 tin_grit = "Tin Grit"
 iron_dust = "Iron Dust"
 gold_dust = "Gold Dust"
 copper_dust = "Copper Dust"
 tin_dust = "Tin Dust"
 bronze_dust = "Bronze Dust"
 steel_dust = "Steel Dust"
 copper_ingot = "Copper Ingot"
 tin_ingot = "Tin Ingot"
 bronze_ingot = "Bronze Ingot"
 steel_ingot = "Steel Ingot"
 copper_nugget = "Copper Nugget"
 tin_nugget = "Tin Nugget"
 bronze_nugget = "Bronze Nugget"
 steel_nugget = "Steel Nugget"
 iron_gear = "Iron Gear"
 gold_gear = "Gold Gear"
 copper_gear = "Copper Gear"
 tin_gear = "Tin Gear"
 bronze_gear = "Bronze Gear"
 steel_gear = "Steel Gear"
 iron_plate = "Iron Plate"
 gold_plate = "Gold Plate"
 copper_plate = "Copper Plate"
 tin_plate = "Tin Plate"
 bronze_plate = "Bronze Plate"
 steel_plate = "Steel Plate"
 bronze_sword = "Bronze Sword"
 bronze_shovel = "Bronze Shovel"
 bronze_pickaxe = "Bronze Pickaxe"
 bronze_axe = "Bronze Axe"
 bronze_hoe = "Bronze Hoe"
 steel_sword = "Steel Sword"
 steel_shovel = "Steel Shovel"
 steel_pickaxe = "Steel Pickaxe"
 steel_axe = "Steel Axe"
 steel_hoe = "Steel Hoe"

[itemGroup.flux]
 items = "Flux Items"

[block.flux]
 fluxgen = "Flux Generator"
 grinding_mill = "Grinding Mill"
 alloy_caster = "Alloy Caster"
 washer = "Washer"
 compactor = "Compactor"
 copper_ore = "Copper Ore"
 tin_ore = "Tin Ore"
 copper_block = "Block of Copper"
 tin_block = "Block of Tin"
 bronze_block = "Block of Bronze"
 steel_block = "Block of Steel"
 energy_cable = "Energy Cable"
 digger = "Digger"
 farmer = "Farmer"
 butcher = "Butcher"
 mob_pounder = "Mob Pounder"
 item_absorber = "Item Absorber"
 rrtable = "Recipe Research Table"
 online_market = "Online Market"
 interactor_rail = "Interactor Rail"
 signal_controller = "Signal Controller"
 copier = "Copier"

[container.flux]
 fluxgen = "Flux Generator"
 grinding_mill = "Grinding Mill"
 alloy_caster = "Alloy Caster"
 washer = "Washer"
 compactor = "Compactor"
 online_market = "Online Market"
 signal_controller = "Signal Controller"
 copier = "Copier"

[gui.flux]
 type_channel = "Type channel number"

[gui.flux.signal_controller]
 mode0 = "Emit to Redstone"
 mode1 = "Set signal"
 mode2 = "Clear signal"
 mode3 = "Set from Redstone"


[gui.flux.recipebook.toggleRecipes]
 grindable = "Showing grindable only"
 alloyable = "Showing alloyable only"
 washable = "Showing washable only"
 compactable = "Showing compactable only"
 copyable = "Showing copyable only"

[gui.flux.jei.category]
 grinding = "Grinding"
 alloying = "Alloying"
 washing = "Washing"
 compacting = "Compacting"
 copying = "Copying"

[entity.minecraft.villager.flux]
 flux_engineer = "Flux Engineer"
