modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Szewek/Flux/issues"
license="MIT"

[[mods]]
 modId="flux"
 version="${modVersion}"
 displayName="Flux"
 updateJSONURL="https://raw.githubusercontent.com/Szewek/Flux/master/update.json"
 displayURL="https://www.curseforge.com/minecraft/mc-mods/flux"
 logoFile="flux_logo.png"
 credits="Szewek"
 authors="Szewek"
 description='''
Flux is a mod which provides energy to Vanilla blocks (like Furnace) without additional items.
It comes with useful machines that make item processing even more interesting.
'''

[[dependencies.flux]]
 modId="forge"
 mandatory=true
 versionRange="[34,)"
 ordering="NONE"
 side="BOTH"

[[dependencies.flux]]
 modId="minecraft"
 mandatory=true
 versionRange="[1.16.3]"
 ordering="NONE"
 side="BOTH"

[[dependencies.flux]]
 modId="fl"
 mandatory=true
 versionRange="[4.3,)"
 ordering="BEFORE"
 side="BOTH"